# docker-compose.yml
version: "3.8"
services:
  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_KEYSPACE=user_db
    ports:
      - "9042:9042"
    networks:
      - mynetwork

  app:
    build: .
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_KEYSPACE=user_db
      - APP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
