version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    networks:
      - app-network
    environment:
      # If your app connects to Cassandra, point it to cassandra:9042
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - app-network
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql

networks:
  app-network:
    driver: bridge
